### PR TITLE
Performance improve for getValue

### PR DESCRIPTION
**Pull request by XenoAmess**
1. change all tabs in all java source codes to spaces.  …
2. increase performance for getValue and getCode functions for enums.  …

### CODE REVIEW

**Comment by XenoAmess** [comment]
@code-disaster review please...

**Comment by code-disaster** [comment]
> change all tabs in all java source codes to spaces. …

Dear Sir, after a quick look I found exactly one source file - which is a test class, even - which mistakenly uses spaces instead of tabs. So, please don't do that. And if you do, please create a separate PR.

> increase performance for getValue and getCode functions for enums. …

While I see and agree with your point made here, I'm not a fan of your _one size fits all_ implementation, to be honest.

- For _some_ enums (SteamAPICallFailure, SteamUniverse, ItemPreviewType) ranges are so small I don't see a problem with doing a linear search.
- Numeric ranges for others (ChatEntryType) are linear anyways, so a more reasonably written lookup function would be just as fine.
- In case of HTTPStatusCode, your solution creates a lookup array with size=600, with only 44 elements used. I'd either use a different storage, or again, a better lookup function.

**Comment by XenoAmess** [comment]
@code-disaster well yes it use 600+ empty enum slot. But I think this shall be 40 times faster than the original code. And in morden computer 600 empty enum slot is not a big cost (considering PC for games always have more than 16g memory these days). So in my opinion it's worth it.

**Comment by AlrikG** [comment]
Why not simply using a static hashmap inside the enums? It also has a runtime of O(1) instead of O(n) and in worst case you have 16 empty slots.

**Comment by code-disaster** [comment]
Yes, for example. Or as I said, be less stupid/lazy with your lookup function. See my last commit.

I know, this isn't O(1), but hey, how frequent do we call this anyway?

**Comment by XenoAmess** [comment]
> Why not simply using a static hashmap inside the enums? It also has a runtime of O(1) instead of O(n) and in worst case you have 16 empty slots.

no, HasMapis o(1) but it is far slower, because of the hash process.
and it saves a Node<K,V>[] table inside HasMap, means it also waste some memory.
so it might be both slower / use more memory to use HasMap here.

So in my opinion...
1. If you think readability is more important here then your older code has best readability.
2. If you think you want it faster but not use spare memory, then try a binary search.
3. If you think some memory cost is standable you can use the way I put here in this commit.

> Yes, for example. Or as I said, be less stupid/lazy with your lookup function. See my last commit.
> 
> I know, this isn't O(1), but hey, how frequent do we call this anyway?
Yeah this is a good question. Maybe I went over-optimize here again = =

**Pull request closed without merging**
