### PR TITLE
added : GetItemInstallInfo, GetItemDownloadInfo, RequestUGCDetails

### PR DESCRIPTION
**Pull request by titoasty**
methods added :
* GetItemInstallInfo
* GetItemDownloadInfo
* RequestUGCDetails

new fields in SteamUGCDetails :
* votesUp
* votesDown
* ownerID
* timeCreated : unix timestamp
* timeUpdated : unix timestamp

For unix timestamps, just use : new Date((long) timeCreated * 1000)
(I think you could add it somewhere in faq)

### CODE REVIEW

**Comment by titoasty** [comment]
there is a little bug, fixed but not yet pushed in requestUGCDetails : it does not copy fileHandle and previewFileHandle. I'll push it this evening (GMT+1 :P)

**Comment by code-disaster** [comment]
Nice work! I'm looking into some modifications though:

- RequestUGCDetails() is marked deprecated in the Steam API. I'll leave it as is, but I'll add createQueryUGCDetailsRequest() as well.
- GetItemInstallInfo()/GetItemDownloadInfo(): I'd like to restrict the API to data which is queried by those functions. You've added a couple of extra fields there, and do a lot of JNI work on the native side which shouldn't be necessary. I'd rather leave this to the user application.

As soon as I'm done, I'll push my changes in a separate branch so you can see what I babble about. ;)

**Comment by titoasty** [comment]
GetItemInstallInfo()/GetItemDownloadInfo() : extra data, you mean converting long to SteamPublishedFileID for example ? this kind of "temporary" field ?

RequestUGCDetails : I didn't know if there were a better way to send SteamUGCDetails_t to java, I passed useful fields as parameters but it's quite inefficient to maintain (and add new fields). Do you know a better way ?

**Comment by code-disaster** [comment]
- Extra data: yes, you basically store redundant data in the info structures: the return code of the function calls ("available", "installed"), and parameters you already know ("publishedFileID"). In getItemInstallInfo() there's a memory leak too.
- Your UGCDetails changes are fine, it's just that the Valve headers say RequestUGCDetails() shouldn't be used anymore.

**Comment by code-disaster** [comment]
Ok, pushed my changes to the "titoasty-ugc" branch.

**Comment by code-disaster** [comment]
I merged my branch back to master recently. Let me know if you run into issues with my changes.

**Comment by code-disaster** [comment]
I'm closing this PR because its changes conflict with the main branch now. Please open a new issue or PR if something's missing.

**Comment by titoasty** [comment]
Sorry was very busy since a few months.. no problem, thanks

**Pull request closed without merging**
