### PR TITLE
SteamUGC.createQueryAllUGCRequest

### PR DESCRIPTION
**Pull request by titoasty**
added SteamUGC.createQueryAllUGCRequest to query all workshop items

### CODE REVIEW

**Comment by code-disaster** [comment]
Note: I renamed the enum (removed the "All*") to match the native part.

**Comment by titoasty** [comment]
Great thanks.
Next, I'll integrate subscribeItem/unsubscribeItem. In SteamRemoteStorage, right ?

**Comment by code-disaster** [comment]
I find them in ISteamUGC when searching the C++ interface, so they should go to SteamUGC as well.

**Comment by titoasty** [comment]
erf... that's what I wanted to say...

**Pull request merged**
