### PR TITLE
UGC : SubscribeItem, UnsubscribeItem, GetNumSubscribedItems, GetSubscribedItems

### PR DESCRIPTION
**Pull request by titoasty**
UnsubscribeItems doesn't work correctly and I can't find why. The call is correctly made and here is what I see in the workshop_log.txt when testing :

[2015-05-28 20:18:25] Detected workshop change for AppID 365*** : removed unsubscribed item 448673330

So this would mean that everything is working correctly.
But the return status code is 0, instead of 1 for Ok.
Could you have a look please ?

(SubscribeItem, GetNumSubscribedItems and GetSubscribedItems are working correctly)

### CODE REVIEW

**Comment by code-disaster** [comment]
Good ol' copy'n paste issue. From the Steam docs: "The CallResult type is RemoteStorage**Un**subscribePublishedFileResult_t", so it looks like you are just using the wrong callback result type in native code.

**Comment by titoasty** [comment]
damn, I'm still not used with steam doc/sdk. I'll fix it soon

**Comment by code-disaster** [comment]
Fixed it along with the merge. Hope you don't mind. ;)

**Comment by titoasty** [comment]
Definitely not, thanks :)

**Pull request merged**
